In [2]:
import numpy as np
from collections import deque

In [3]:
# a
arr1=np.arange(0,10)
print(arr1)

# b
zeros=np.zeros((3,3))
print(zeros)

# c
identity=np.eye(4)
print(identity)

# d
between=np.linspace(0,1,10)
print(between)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [4]:
arr2d=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr2d.shape)
print("Data type:",arr2d.dtype)
print("Dimensions:",arr2d.ndim)
print("Size:",arr2d.size)

Shape: (2, 3)
Data type: int64
Dimensions: 2
Size: 6


In [5]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Middle element:",arr[1,1])
print("Last column:",arr[:,2])
print("First two rows:\n",arr[:2,:])
print("Values > 50:",arr[arr>50])

Middle element: 50
Last column: [30 60 90]
First two rows:
 [[10 20 30]
 [40 50 60]]
Values > 50: [60 70 80 90]


In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Element-wise multiplication:",a*b)
print("Dot product:",np.dot(a,b))
print("Mean of b:",np.mean(b))
print("Std of b:",np.std(b))

Addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Dot product: 32
Mean of b: 5.0
Std of b: 0.816496580927726


In [7]:
A=np.array([1,2,3])
B=np.array([4,5,6])
num=A**2+np.sin(B)
den=np.sqrt(np.abs(A-B))+1
Z=num/den

print(Z)


[0.08901646 1.11311097 3.19195546]


In [8]:
arr = np.random.randint(-50, 151, size=100)
arr_reshaped = arr.reshape((10, 10))
arr_reshaped[arr_reshaped < 0] = 0
arr_min = arr_reshaped.min()
arr_max = arr_reshaped.max()
normalized = (arr_reshaped - arr_min) / (arr_max - arr_min)
row_means = normalized.mean(axis=1)
print("Original reshaped array (negatives replaced):\n", arr_reshaped)
print("\nNormalized array:\n", normalized)
print("\nRow-wise means:\n", row_means)

Original reshaped array (negatives replaced):
 [[  0  23   0  45 137   3  63 136   0 149]
 [100 139 131   0 107 124   0 146  17   0]
 [130  47  58  31   0   0  58   0  72  57]
 [120   0 132  38 116   9  26 123  51  40]
 [134  12  29  47  61  82 116 108   0  49]
 [ 27   0   0 141   0 139   0   0  69  46]
 [ 77  89  90  82  37  75   0  37 106  67]
 [107 103  42   0  98   0 149   0   0  61]
 [ 69   0  66   0   0 130   6   0  94  92]
 [144   0 119  99 115  89  70   0  97  95]]

Normalized array:
 [[0.         0.15436242 0.         0.30201342 0.91946309 0.02013423
  0.42281879 0.91275168 0.         1.        ]
 [0.67114094 0.93288591 0.87919463 0.         0.71812081 0.83221477
  0.         0.97986577 0.11409396 0.        ]
 [0.87248322 0.31543624 0.38926174 0.20805369 0.         0.
  0.38926174 0.         0.48322148 0.38255034]
 [0.80536913 0.         0.88590604 0.25503356 0.77852349 0.06040268
  0.17449664 0.82550336 0.34228188 0.26845638]
 [0.89932886 0.08053691 0.19463087 0.31543624 0.40

Explanation:
1. The code creates random numbers, reshapes them into 10x10, and replaces negatives with 0.
2. Then it normalizes values between 0 and 1.
3. Finally, it computes the mean of each row.

In [9]:
arr=np.arange(1,13)
matrix=arr.reshape(3,4)
print(matrix)
print("Row-wise std:", np.std(matrix,axis=1))
print("Column-wise std:", np.std(matrix,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row-wise std: [1.11803399 1.11803399 1.11803399]
Column-wise std: [3.26598632 3.26598632 3.26598632 3.26598632]


In [10]:
def reverse_string(s):
    stck=[]
    for ch in s:
        stck.append(ch)
    rev=''
    while stck:
        rev+=stck.pop()
    return rev

print(reverse_string("hello"))

olleh


In [11]:
def reverse_first_k(queue, k):
    stack=[]
    for _ in range(k):
        stack.append(queue.popleft())
    while stack:
        queue.appendleft(stack.pop())
    return list(queue)

q = deque([1,2,3,4,5])
print(reverse_first_k(q,3))

[1, 2, 3, 4, 5]


In [ ]:
def read_cube(filename):
    cube=[]
    with open(filename,'r') as f:
        for line in f:
            cube.append(list(map(int,line.strip().split())))
    return cube

def get_neighbors(pos, cube):
    x,y=pos
    dirs=[(1,0),(-1,0),(0,1),(0,-1)]
    n,m=len(cube), len(cube[0])
    neighbors=[]
    for dx,dy in dirs:
        nx,ny=x+dx,y+dy
        if 0<=nx<n and 0<=ny<m and cube[nx][ny]==0:
            neighbors.append((nx,ny))
    return neighbors

def bfs(cube):
    n,m=len(cube),len(cube[0])
    start,goal=(0,0),(n-1,m-1)
    queue=deque([[start]])
    visited=set([start])
    while queue:
        path=queue.popleft()
        x,y=path[-1]
        if (x,y)==goal:
            return path
        for nei in get_neighbors((x,y),cube):
            if nei not in visited:
                visited.add(nei)
                queue.append(path+[nei])
    return -1

def dfs(cube):
    n,m=len(cube),len(cube[0])
    start,goal=(0,0),(n-1,m-1)
    stack=[[start]]
    visited=set([start])
    while stack:
        path=stack.pop()
        x,y=path[-1]
        if (x,y)==goal:
            return path
        for nei in get_neighbors((x,y),cube):
            if nei not in visited:
                visited.add(nei)
                stack.append(path+[nei])
    return -1

cube=read_cube('cube.txt')
print("BFS path:", bfs(cube))
print("DFS path:", dfs(cube))

BFS path: [(0, 0), (0, 1), (1, 1), (2, 1), (2, 2), (2, 3), (2, 4), (3, 4), (4, 4)]
DFS path: [(0, 0), (0, 1), (1, 1), (2, 1), (2, 2), (2, 3), (2, 4), (3, 4), (4, 4)]
